name: Inovercy
favicon: null
layout_spectrum: 1
typography_spectrum: 0.07527869311161339
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eaf0ee'
    - '#0f0909'
    - '#986f59'
    - '#2877d3'
    - '#52b3e0'
  brandStrength: 0.6643922964576632
  lightness: 0.2903479957021773
  saturation: 0.6455204309895635
  rhythmicContrast: 0.44520904938690364
purpose: []
